name: Compile test

on:
  pull_request:
    paths:
      - ".github/workflows/test.yml"
      - "library.properties"
      - "examples/**"
      - "src/**"
  push:
    paths:
      - ".github/workflows/test.yml"
      - "library.properties"
      - "examples/**"
      - "src/**"
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.board.fqbn }}
    runs-on: ubuntu-latest

    env:
      LIBRARIES: |
        # Install the Arduino_ConnectionHandler library from the repository
        - source-path: ./
      ARDUINOCORE_MBED_STAGING_PATH: extras/ArduinoCore-mbed
      ARDUINOCORE_API_STAGING_PATH: extras/ArduinoCore-API
      SKETCHES_PATH: ./
      SKETCHES_REPORTS_PATH: sketches-reports
    strategy:
      matrix:
        board:
          - fqbn: "esp32:esp32:esp32"
            platform-name: esp32:esp32

        # Make board type-specific customizations to the matrix jobs
        include:
          - board:
              platform-name: esp32:esp32
            platforms: |
              # Install ESP32 platform via Boards Manager
              - name: esp32:esp32
                source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

    steps:
      - uses: actions/checkout@v3

      - name: Install ESP32 platform dependencies
        if: matrix.board.platform-name == 'esp32:esp32'
        run: pip3 install pyserial

      - name: Compile test
        uses: arduino/compile-sketches@v1
        with:
          platforms: ${{ matrix.platforms }}
          fqbn: ${{ matrix.board.fqbn }}
          libraries: ${{ env.LIBRARIES }}
          enable-deltas-report: 'true'
          sketch-paths: ${{ env.SKETCHES_PATH }}
          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}

      - name: Save memory usage change report as artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          name: ${{ env.SKETCHES_REPORTS_PATH }}
          path: ${{ env.SKETCHES_REPORTS_PATH }}
